name: google_maps_talk
description: Exploring the new Google NavigationSDK for Flutter and future
  changes to Google Maps
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.3
  flutter: 3.24.3

dependencies:
  api_client:
    path: packages/api_client
  bloc: ^8.1.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.3
  google_maps_talk_ui:
    path: packages/google_maps_talk_ui
  google_navigation_flutter: ^0.3.0
  http: ^1.2.2
  intl: ^0.19.0
  location_repository:
    path: packages/location_repository
  map_launcher: ^3.5.0
  maps_examples:
    path: packages/maps_examples
  url_launcher: ^6.3.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
