name: location_repository
description: Location package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.24.3

dependencies:
  api_client:
      path: ../api_client
  equatable: ^2.0.5
  geolocator: ^12.0.0
  json_annotation: ^4.8.1


dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.25.2
  very_good_analysis: ^5.1.0
