name: maps_examples
description: MapsExamples flutter package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter
  google_navigation_flutter: ^0.3.0
  http: ^1.2.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
